### ISSUE TITLE
The program crashed

### ISSUE THREAD

**Issue by panovr** [qtexe/qt_2019_ncov#2]
Hi,
  I build the program with qtcreator and qt 5.15.2, and start the program.
  However, the program crashed after the program GUI started and running for several seconds.

**Comment by qtexe** [comment]
**This is normal.**

- API interface is closed
- API interface json data format change

**Comment by panovr** [comment]
Hi,
  [this line](https://github.com/qtexe/qt_2019_ncov/blob/master/dialog.h#L102) `QString data1_Api = "http://view.inews.qq.com/g2/getOnsInfo?name=disease_h5&_="`
should be  `QString data1_Api = "https://view.inews.qq.com/g2/getOnsInfo?name=disease_h5&_="`
